### PR TITLE
latest protobuf changes and compilation

### PR DESCRIPTION
**Pull request by mreiferson**
this updates the code to the latest goprotobuf changes cc @ha

### CODE REVIEW

**Comment by mreiferson** [comment]
this compiles but i have a few tests that are hanging, will update when I figure out why.

**Comment by mreiferson** [comment]
FYI this also depends on ha/doozer#21

**Comment by mreiferson** [comment]
ok, all tests passing

**Comment by bketelsen** [comment]
All tests pass.  LGTM

**Pull request merged**
