### PR TITLE
Go1 fixes

### PR DESCRIPTION
**Pull request by 4ad**

### CODE REVIEW

**Comment by 4ad** [comment]
Sorry for the multiple pull request noise, git is not my friend, I'm a mercurial guy.

**Comment by fd** [comment]
any progress on this?

**Comment by divoxx** [comment]
Pull request addressing Go1 compatibility at #31

**Comment by 4ad** [comment]
I don't understand your unrelated pull request since _this_ pull request already exists and works.

**Comment by divoxx** [comment]
Oh, I actually Aram's commits and only checked 4ad's.

I just did a fresh clone and tried to install it under Go1 so I endup fixing them, my bad. Those changes haven't been merged back to master though, right?

**Comment by divoxx** [comment]
I've close my pull request. _need sleep_

**Pull request merged**
